# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Check output
      run: echo ${{ github.event.pull_request.head.ref }}   
    
#     - name: Set output
#       id: vars
#       run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

#     - name: Check output
#       run: echo ${{ steps.vars.outputs.short_ref }}
 #   
    
#     - name: Set up Python 3.10
#       uses: actions/setup-python@v4
#       with:
#         python-version: "3.10"
#     - run: python code/${{ github.event.head_commit.message }}/run.py 

